<div id='wrap'>
	<h2>Are you sure you want to uninstall News & Events?</h2>
	<p>
		<b>All your News & Events data will be permanently erased.</b> You cannot undo this action. Are you sure you want to continue?
	</p>
	<p>
		<a href='admin.php?page=<?php echo ne_get_plugin_folder() ?>/newsAndEvents&action=uninstall'><input type='button' class='button-primary' value = 'Uninstall News & Events &raquo;' /></a>
	</p>
</div>

